### ISSUE TITLE
Why printing config array gives empty Array?

### ISSUE THREAD

**Issue by lnt** [opensolutions/smarty#3]
$tpl = new Smarty();
$tpl->configLoad('compose.conf');
$config = $tpl->getConfigVars();
print_r($config);

it returns

Array()

**Comment by barryo** [comment]
The description for this repo states:

> Clone of the distribution trunk of the PHP Smarty templating engine. Sync'd hourly by our servers.

I.e., this is a **clone**. A pure clone.
